Name = input('Введите ваше имя: ')
Age = input('Введите ваш возраст: ')
City = input('Введите ваш город: ')
print('Привет, меня зовут %s. Мне %s. Я живу в городе %s' % (Name, Age, City))
print('Привет, меня зовут {Name}. Мне {Age}. Я живу в городе {City}'.format(Name=Name, Age=Age, City=City))
print(f'Привет, меня зовут {Name}. Мне {Age}. Я живу в городе {City}')
