Name = input('Введите ваше имя: ')
Age = input('Введите ваш возраст: ')
City = input('Введите ваш город: ')
print('Меня зовут %s. Мне %s. Я живу в городе %s' % (Name, Age, City))
print('Меня зовут {}. Мне {}. Я живу в городе {}'.format(Name, Age, City))
print(f'Меня зовут {Name}. Мне {Age}. Я живу в городе {City}')
