Name = input('Введите ваше имя: ')
Age = input('Введите ваш возраст: ')
City = input('Введите ваш город: ')
print(f'Меня зовут {Name}. Мне {Age}. Я живу в городе {City}'.format(Name=Name, Age=Age, City=City))
print(f'Меня зовут {Name}. Мне {Age}. Я живу в городе {City}')
