Name = input('Введите ваше имя: ')
Age = input('Введите ваш возраст: ')
City = input('Введите ваш город: ')
print('Меня зовут {Name}. Мне {Age}. Я живу в городе {City}'.format(Name=Name, Age=Age, City=City))
print('Меня зовут {}. Мне {}. Я живу в городе {}'.format(Name, Age, City))
print(f'Меня зовут {Name}. Мне {Age}. Я живу в городе {City}')
